Refactor all scripts to use printf and refactor sysup to try and troubleshoot the issue with total_updates

diff --git a/scripts/add_font b/scripts/add_font
--- a/scripts/add_font
+++ b/scripts/add_font
@@ -9,9 +9,9 @@ show_help() {
   print_header "Usage: $(basename $0) <url>"
   echo "This script downloads and installs a font from a specified URL."
   print_header "Options:"
-  echo "  $(color_bold_blue 'url')        The URL of the font zip file to download."
+  printf "${BLUE_BOLD}url${ENDL}        The URL of the font zip file to download."
   print_header "Examples:"
-  echo "  $(color_blue "$(basename "$0") https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip")"
+  printf "${BLUE}$(basename "$0") https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip${ENDL}"
   exit 0
 }
 
@@ -21,7 +21,7 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 fi
 
 if [ -z "$1" ]; then
-  color_red "Error: No URL provided."
+  printf "${RED}Error: No URL provided.${ENDL}"
   show_help
 fi
 
@@ -38,7 +38,7 @@ filename=$(basename "$url")
 wget -P ~/.local/share/fonts "$url"
 
 # Navigate to the fonts directory
-cd ~/.local/share/fonts || { color_red "Error: Failed to navigate to the fonts directory."; exit 1; }
+cd ~/.local/share/fonts || { printf "${RED}Error: Failed to navigate to the fonts directory.${ENDL}"; exit 1; }
 
 # Unzip the downloaded file
 unzip "$filename"
@@ -51,3 +51,4 @@ fc-cache -fv
 
 # Title indication
 print_title "FONT INSTALLATION SCRIPT COMPLETED"
+
diff --git a/scripts/bash_utilities b/scripts/bash_utilities
--- a/scripts/bash_utilities
+++ b/scripts/bash_utilities
@@ -1,35 +1,32 @@
 #!/bin/bash
 
-# Color functions
-# Display text in green
-color_green() {
-  echo -e "\033[32m$1\033[0m"
-}
+# Define ANSI escape codes as variables
+NC="\033[0m"
+ENDL="${NC}\n" 
 
-# Display text in red
-color_red() {
-  echo -e "\033[31m$1\033[0m"
-}
+# Color codes
+RED="\033[31m"
+ORANGE="\033[38;5;208m"
+YELLOW="\033[33m"
+GREEN="\033[32m"
+BLUE="\033[38;5;33m"
+INDIGO="\033[38;5;54m"
+VIOLET="\033[38;5;93m"
 
-# Display text in blue
-color_blue() {
-  echo -e "\033[38;5;33m$1\033[0m"
-}
+# Extra colors
+CYAN="\033[36m"
+PINK="\033[38;5;213m"
+WHITE="\033[97m"
+BLACK="\033[30m"
+GRAY="\033[90m"
 
-# Display text in bold blue
-color_bold_blue() {
-  echo -e "\033[1;34m$1\033[0m"
-}
-
-# Display text in orange
-color_orange() {
-  echo -e "\033[38;5;208m$1\033[0m"
-}
-
-# Display text in cyan
-color_cyan() {
-  echo -e "\033[36m$1\033[0m"
-}
+# Text Styles
+UNDERLINE="\033[4m"
+ITALIC="\033[3m"           # Limited support
+BLINK="\033[5m"            # Limited support
+REVERSE="\033[7m"
+DIM="\033[2m"
+STRIKETHROUGH="\033[9m"    # Limited support
 
 # Function to print a section header
 print_header() {
@@ -37,29 +34,29 @@ print_header() {
   local length=${#header}
   local border=$(printf "%-${length}s" " " | sed "s/ /─/g")
   echo ""
-  color_orange "$header"
-  color_orange "$border"
+  printf "${ORANGE}$header${ENDL}"
+  printf "${ORANGE}$border${ENDL}"
 }
 
 # Function to print a centered title with a full-width border
 print_title() {
-  local title="$1"
-  local title_upper=$(echo "$title" | tr '[:lower:]' '[:upper:]')  # Convert title to uppercase
-  local width=$(tput cols)  # Get the current terminal width
-  local title_length=${#title_upper}
-  local border_length=$(( (width - title_length - 2) / 2 ))  # Calculate border length for both sides
+  local TITLE="$1"
+  local TITLE_UPPER=$(echo "$TITLE" | tr '[:lower:]' '[:upper:]')  # Convert title to uppercase
+  local WIDTH=$(tput cols)  # Get the current terminal width
+  local TITLE_LEN=${#TITLE_UPPER}
+  local BORDER_LEN=$(( (WIDTH - TITLE_LEN - 2) / 2 ))  # Calculate border length for both sides
 
   # Create the border using the line character
-  local border=$(printf "%-${border_length}s" " " | sed "s/ /─/g")  # Replace spaces with lines
+  local BORDER=$(printf "%-${BORDER_LEN}s" " " | sed "s/ /─/g")  # Replace spaces with lines
 
   # Print the full-width line with the title centered
-  color_cyan "${border} ${title_upper} ${border}"
+  printf "${CYAN}${BORDER} ${TITLE_UPPER} ${BORDER} ${ENDL}"
 }
 
 # Function to log a message with a timestamp
 log_message() {
   local message="$1"
-  echo -e "$(color_cyan "$(date '+%Y-%m-%d %H:%M:%S')") - $message"
+  echo -e "$(echo_cyan "$(date '+%Y-%m-%d %H:%M:%S')") - $message"
 }
 
 # Function to handle errors and log a message
@@ -84,7 +81,7 @@ confirm_action() {
 
 # Function to check if a command is installed
 check_dependency() {
-  command -v "$1" >/dev/null 2>&1 || { echo >&2 "$(color_red "Error: $1 is not installed. Please install it.")"; exit 1; }
+  command -v "$1" >/dev/null 2>&1 || { echo >&2 "$(echo_red "Error: $1 is not installed. Please install it.")"; exit 1; }
 }
 
 # Function to pause execution for a specified number of seconds
diff --git a/scripts/clean_empty_dirs b/scripts/clean_empty_dirs
--- a/scripts/clean_empty_dirs
+++ b/scripts/clean_empty_dirs
@@ -7,13 +7,15 @@ source "$(dirname "$0")/bash_utilities"
 show_help() {
   print_title "HELP INFORMATION"
   print_header "Usage: $(basename "$0") [OPTIONS] [DIRECTORY]"
-  echo "This script finds and deletes empty directories."
+  printf "${BLUE}This script finds and deletes empty directories.${ENDL}"
+
   print_header "Options:"
-  echo -e "  $(color_bold_blue "-h, --help")     Display this help message."
-  echo -e "  $(color_bold_blue "[DIRECTORY]")    The directory to search for empty directories. If not provided, defaults to the current directory."
+  printf "${BOLD_BLUE}  -h, --help${ENDL}     ${BLUE}Display this help message.${ENDL}"
+  printf "${BOLD_BLUE}  [DIRECTORY]${ENDL}    ${BLUE}The directory to search for empty directories. If not provided, defaults to the current directory.${ENDL}"
+  
   print_header "Examples:"
-  echo -e "  $(color_blue "$(basename "$0") /path/to/directory")  Find and delete empty directories in the specified directory."
-  echo -e "  $(color_blue "$(basename "$0")")                     Find and delete empty directories in the current directory."
+  printf "${BLUE}  $(basename "$0") /path/to/directory${ENDL}  ${BLUE}Find and delete empty directories in the specified directory.${ENDL}"
+  printf "${BLUE}  $(basename "$0")${ENDL}                     ${BLUE}Find and delete empty directories in the current directory.${ENDL}"
   exit 0
 }
 
@@ -25,7 +27,7 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
       show_help
       ;;
     * )
-      echo "Invalid option: $1" 1>&2
+      printf "${RED}Invalid option: $1${ENDL}" 1>&2
       show_help
       ;;
   esac
@@ -41,7 +43,7 @@ fi
 
 # Check if the provided target is a directory
 if [ ! -d "$target_dir" ]; then
-  color_red "Error: $target_dir is not a valid directory."
+  printf "${RED}Error: $target_dir is not a valid directory.${ENDL}"
   exit 1
 fi
 
@@ -54,16 +56,16 @@ empty_dirs=$(find "$target_dir" -type d -empty)
 
 # Output each empty directory before deletion
 if [ -n "$empty_dirs" ]; then
-  echo "The following empty directories will be deleted:"
+  printf "${BLUE}The following empty directories will be deleted:${ENDL}"
   echo "$empty_dirs"
   
   # Ask for confirmation before deletion
   if confirm_action "Do you want to proceed with deletion? (y/n)"; then
     # Delete the empty directories
     find "$target_dir" -type d -empty -delete
-    echo "Empty directories have been deleted."
+    printf "${GREEN}Empty directories have been deleted.${ENDL}"
   else
-    echo "Deletion canceled."
+    printf "${YELLOW}Deletion canceled.${ENDL}"
   fi
 else
   echo "No empty directories found in $target_dir."
@@ -71,3 +73,4 @@ fi
 
 # End operation
 print_title "EMPTY DIRECTORY DELETION COMPLETE"
+echo "Directory: file//:$target_dir"
